#!/bin/bash
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
#############################
### This script sets up two loopback virtual devices and a null sink
### which can then be used to mix inputs and record the result.
### It requires a functioning PulseAudio installation and also
### PulseAudio Volume Control to manage the streams.
# Version: 0.2.0
# License: GPL 2
# Author: clareoldie  <clareoldie@gmail.com>
# Date: Aug 11 2013
#
set -x
#
unload-modules () {
for i in $(pactl list | grep -B 2 '=Mixer1' | grep 'Module #' | cut -d '#' -f 2-)
do
pactl unload-module $i
done
}

load-modules () {
### Load required modules
pactl load-module module-null-sink sink_name=Mixer1 sink_properties="device.description='Mixer#1'"
pactl load-module module-loopback sink=Mixer1
pactl load-module module-loopback sink=Mixer1
}

test-modules () {
## If the modules exist 0$?=0 then unload them, else load them.
pactl list | grep -B 1 'Name: module-loopback'
if [ "$?" = "0" ]
then
unload-modules
exit 0
fi
pactl list | grep -B 1 'Name: module-null-sink'
if [ "$?" = "0" ]
then
unload-modules
exit 0
else
load-modules
fi
}

### Main Programme
test-modules
